# NUMPY

In [9]:
import numpy as np

arr1=np.array([1,2,3,4])
print("1d array: ",arr1)

1d array:  [1 2 3 4]


In [10]:
arr2=np.array([[1,2,3],[4,5,6]])
print("2D array:",arr2)

2D array: [[1 2 3]
 [4 5 6]]


## list vs numpy

In [11]:
list1=[1,2,3]
print(list1*2)

[1, 2, 3, 1, 2, 3]


In [12]:
arr1=np.array([1,2,3])
print(arr1*2)      #element wise multiplication

[2 4 6]


### CREATING ARRAY FROM SCRATCH

In [14]:
zeros1=np.zeros((3,4))
zeros1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
a1=np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
full=np.full((2,2),7)
full

array([[7, 7],
       [7, 7]])

In [18]:
random=np.random.random((2,3))
random

array([[0.67918072, 0.16102722, 0.73423813],
       [0.23247066, 0.25322327, 0.26943323]])

In [19]:
sequence=np.arange(0,10,2)
sequence

array([0, 2, 4, 6, 8])

## Vecto, Matrix and Tensor

In [20]:
vector=np.array([1,2,3])
vector

array([1, 2, 3])

In [21]:
matrix=np.array([[1,2,3],[4,5,6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
tensor=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Array properties

In [29]:
arr=np.array([[1,2,3],
             [4,5,6]])
print("Shape of array: ",arr.shape)
print("Dimension of array: ",arr.ndim)
print("Size of array: ",arr.size)
print("Datatype of array: ",arr.dtype)


Shape of array:  (2, 3)
Dimension of array:  2
Size of array:  6
Datatype of array:  int64


### Array reshaping

In [ ]:
arr1=np.arange(6)
arr2=np.arange(12)
reshaped=arr2.reshape((3,4))
print(arr2)

flattened=reshaped.flatten()
print(arr2)

# returns view(original) instead of copy 
raveled=reshaped.ravel()
print(raveled)



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Transpose

In [41]:
arr1=np.array([[12,33,4,46],[34,78,87,90]])
transposed=arr1.T
print(transposed)

[[12 34]
 [33 78]
 [ 4 87]
 [46 90]]
