# Numpy Array Operation

In [5]:
import numpy as np


In [6]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing: ",arr1[2:5])
print("step slicing: ",arr1[2:5:2])
print("Negative slicing: ",arr1[-4:-1])

Basic slicing:  [3 4 5]
step slicing:  [3 5]
Negative slicing:  [6 7 8]


In [7]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific element: ",arr1[0][2])
print("Specific row: ",arr1[:,0])
print("Specific column: ",arr1[0,:])


Specific element:  3
Specific row:  [1 4 7]
Specific column:  [1 2 3]


### Sorting

In [8]:
unsorted_arr=np.array([3,1,4,1,5,6,7,0])

sorted_arr=np.sort(unsorted_arr)
print(sorted_arr)

[0 1 1 3 4 5 6 7]


In [9]:
unsorted_2d=np.array([[1,2],[1,7],[9,0]])
print("Sorted 2d array by column: ",np.sort(unsorted_2d,axis=0))
print("Sorted 2d array by row: ",np.sort(unsorted_2d,axis=1))

Sorted 2d array by column:  [[1 0]
 [1 2]
 [9 7]]
Sorted 2d array by row:  [[1 2]
 [1 7]
 [0 9]]


## Filter


In [10]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
even_number=arr1[arr1%2==0]
print("Even Numbers: ",even_number)

Even Numbers:  [2 4 6 8]


### Filter with markdown cell

In [11]:
mask=arr1>5   #expression in numpy
print("Numer greate than five ",arr1[mask])

Numer greate than five  [6 7 8 9]


### Fancy indexing vs np.where

In [14]:
indices=[0,2,4]
print(arr1[indices])

[1 3 5]


In [16]:
where_result=np.where(arr1>5)
print(arr1[where_result])

[6 7 8 9]


### condition array

In [ ]:
condition_array=np.where(arr1>5,arr1*2,arr1) #(condition,if,else)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18]


### Adding and removing data


In [ ]:
arr1=np.array([4,5,6])
arr2=np.array([7,8,9])
combined=np.concat((arr1,arr2)) 

print(combined)
print(arr1+arr2)

[4 5 6 7 8 9]
[11 13 15]


##### Array compatibility

In [21]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
# same dimension
print("compatibility shape ",a.shape==b.shape)

compatibility shape  True


In [26]:
original=np.array([[1,2,3],[5,6,7]])
new_row=np.array([[9,1,0]])
with_new_row=np.vstack((original,new_row))  #adding new row
print(original)
print(with_new_row)

new_column=np.array([[6],[8]])
with_new_column=np.hstack((original,new_column))
print(with_new_column)

[[1 2 3]
 [5 6 7]]
[[1 2 3]
 [5 6 7]
 [9 1 0]]
[[1 2 3 6]
 [5 6 7 8]]


In [ ]:
a=np.array([1,2,3,4,5,6])
deleted=np.delete(a,2)   #return array after deletion
print(deleted)

[1 2 4 5 6]
