## Advance operation with business examples

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]

sales_data = np.array([
[1, 150000, 180000, 220000, 250000], # Paradise Biryani
[2, 120000, 140000, 160000, 190000], # Beijing Bites
[13, 200000, 230000, 260000, 300000], # Pizza Hub
[4, 180000, 210000, 240000, 270000], # Burger Point
[5, 160000, 185000, 205000, 230000] # Chai Point

])

print("************Zomato Sales Analysis ****************")
print("Shape of the data", sales_data.shape)  

print("\nData of first 3 restaurants: \n",sales_data[:3])

************Zomato Sales Analysis ****************
Shape of the data (5, 5)

Data of first 3 restaurants: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [    13 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]]


In [20]:
#total sales per year:

print(np.sum(sales_data,axis=0))
yearly_total=np.sum(sales_data[:,1:,],axis=0)
print(yearly_total)


# minimum sales per restraurant

min_sales=np.min(sales_data[:,1:],axis=1)
print(min_sales)


# Maximum sales per year

max_sales=np.max(sales_data[:,1:],axis=0)
print(max_sales)


#Average sale per restaurant


avg_sales=np.mean(sales_data[:,1:],axis=1)
print(avg_sales)

[     25  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
[150000 120000 200000 180000 160000]
[200000 230000 260000 300000]
[200000. 152500. 247500. 225000. 195000.]


In [21]:
cumsum=np.cumsum(sales_data[:,1:],axis=1)
print(cumsum)

[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


In [ ]:
vector1=np.array([1,2,3,4,5])
vector2=np.array([6,7,8,9,10])
print("Vector addition", vector1+vector2)
print("Vector multiplication", vector1*vector2)
print("Dot Product: ",np.dot(vector1,vector2))



Vector addition [ 7  9 11 13 15]
Vector multiplication [ 6 14 24 36 50]
Dot Product:  130


In [24]:
names=np.array(["Komal","Vasu","Ryle","Atlas"])   #individually
vectorized_upper=np.vectorize(str.upper)
print(vectorized_upper(names))


['KOMAL' 'VASU' 'RYLE' 'ATLAS']


In [25]:
monthly_avg=sales_data[:,1:]/12    #for integer always broadcast
print(monthly_avg)

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
